// The 114 sūrah names, Arabic and transliterated, so a verse block can name its
// sūrah instead of showing a bare number. Index 0 is sūrah 1.
//
// Transliteration follows the common academic scheme (ʿayn as ʿ, hamza as ʾ,
// emphatic consonants with a dot below), which is what a reader who reads
// English about the Qur'an will recognise.
export type Surah = { arabic: string; latin: string };

const SURAHS: readonly Surah[] = [
  { arabic: "الفاتحة", latin: "Al-Fātiḥah" },
  { arabic: "البقرة", latin: "Al-Baqarah" },
  { arabic: "آل عمران", latin: "Āl ʿImrān" },
  { arabic: "النساء", latin: "An-Nisāʾ" },
  { arabic: "المائدة", latin: "Al-Māʾidah" },
  { arabic: "الأنعام", latin: "Al-Anʿām" },
  { arabic: "الأعراف", latin: "Al-Aʿrāf" },
  { arabic: "الأنفال", latin: "Al-Anfāl" },
  { arabic: "التوبة", latin: "At-Tawbah" },
  { arabic: "يونس", latin: "Yūnus" },
  { arabic: "هود", latin: "Hūd" },
  { arabic: "يوسف", latin: "Yūsuf" },
  { arabic: "الرعد", latin: "Ar-Raʿd" },
  { arabic: "إبراهيم", latin: "Ibrāhīm" },
  { arabic: "الحجر", latin: "Al-Ḥijr" },
  { arabic: "النحل", latin: "An-Naḥl" },
  { arabic: "الإسراء", latin: "Al-Isrāʾ" },
  { arabic: "الكهف", latin: "Al-Kahf" },
  { arabic: "مريم", latin: "Maryam" },
  { arabic: "طه", latin: "Ṭāhā" },
  { arabic: "الأنبياء", latin: "Al-Anbiyāʾ" },
  { arabic: "الحج", latin: "Al-Ḥajj" },
  { arabic: "المؤمنون", latin: "Al-Muʾminūn" },
  { arabic: "النور", latin: "An-Nūr" },
  { arabic: "الفرقان", latin: "Al-Furqān" },
  { arabic: "الشعراء", latin: "Ash-Shuʿarāʾ" },
  { arabic: "النمل", latin: "An-Naml" },
  { arabic: "القصص", latin: "Al-Qaṣaṣ" },
  { arabic: "العنكبوت", latin: "Al-ʿAnkabūt" },
  { arabic: "الروم", latin: "Ar-Rūm" },
  { arabic: "لقمان", latin: "Luqmān" },
  { arabic: "السجدة", latin: "As-Sajdah" },
  { arabic: "الأحزاب", latin: "Al-Aḥzāb" },
  { arabic: "سبأ", latin: "Sabaʾ" },
  { arabic: "فاطر", latin: "Fāṭir" },
  { arabic: "يس", latin: "Yā-Sīn" },
  { arabic: "الصافات", latin: "Aṣ-Ṣāffāt" },
  { arabic: "ص", latin: "Ṣād" },
  { arabic: "الزمر", latin: "Az-Zumar" },
  { arabic: "غافر", latin: "Ghāfir" },
  { arabic: "فصلت", latin: "Fuṣṣilat" },
  { arabic: "الشورى", latin: "Ash-Shūrā" },
  { arabic: "الزخرف", latin: "Az-Zukhruf" },
  { arabic: "الدخان", latin: "Ad-Dukhān" },
  { arabic: "الجاثية", latin: "Al-Jāthiyah" },
  { arabic: "الأحقاف", latin: "Al-Aḥqāf" },
  { arabic: "محمد", latin: "Muḥammad" },
  { arabic: "الفتح", latin: "Al-Fatḥ" },
  { arabic: "الحجرات", latin: "Al-Ḥujurāt" },
  { arabic: "ق", latin: "Qāf" },
  { arabic: "الذاريات", latin: "Adh-Dhāriyāt" },
  { arabic: "الطور", latin: "Aṭ-Ṭūr" },
  { arabic: "النجم", latin: "An-Najm" },
  { arabic: "القمر", latin: "Al-Qamar" },
  { arabic: "الرحمن", latin: "Ar-Raḥmān" },
  { arabic: "الواقعة", latin: "Al-Wāqiʿah" },
  { arabic: "الحديد", latin: "Al-Ḥadīd" },
  { arabic: "المجادلة", latin: "Al-Mujādilah" },
  { arabic: "الحشر", latin: "Al-Ḥashr" },
  { arabic: "الممتحنة", latin: "Al-Mumtaḥanah" },
  { arabic: "الصف", latin: "Aṣ-Ṣaff" },
  { arabic: "الجمعة", latin: "Al-Jumuʿah" },
  { arabic: "المنافقون", latin: "Al-Munāfiqūn" },
  { arabic: "التغابن", latin: "At-Taghābun" },
  { arabic: "الطلاق", latin: "Aṭ-Ṭalāq" },
  { arabic: "التحريم", latin: "At-Taḥrīm" },
  { arabic: "الملك", latin: "Al-Mulk" },
  { arabic: "القلم", latin: "Al-Qalam" },
  { arabic: "الحاقة", latin: "Al-Ḥāqqah" },
  { arabic: "المعارج", latin: "Al-Maʿārij" },
  { arabic: "نوح", latin: "Nūḥ" },
  { arabic: "الجن", latin: "Al-Jinn" },
  { arabic: "المزمل", latin: "Al-Muzzammil" },
  { arabic: "المدثر", latin: "Al-Muddaththir" },
  { arabic: "القيامة", latin: "Al-Qiyāmah" },
  { arabic: "الإنسان", latin: "Al-Insān" },
  { arabic: "المرسلات", latin: "Al-Mursalāt" },
  { arabic: "النبأ", latin: "An-Nabaʾ" },
  { arabic: "النازعات", latin: "An-Nāziʿāt" },
  { arabic: "عبس", latin: "ʿAbasa" },
  { arabic: "التكوير", latin: "At-Takwīr" },
  { arabic: "الانفطار", latin: "Al-Infiṭār" },
  { arabic: "المطففين", latin: "Al-Muṭaffifīn" },
  { arabic: "الانشقاق", latin: "Al-Inshiqāq" },
  { arabic: "البروج", latin: "Al-Burūj" },
  { arabic: "الطارق", latin: "Aṭ-Ṭāriq" },
  { arabic: "الأعلى", latin: "Al-Aʿlā" },
  { arabic: "الغاشية", latin: "Al-Ghāshiyah" },
  { arabic: "الفجر", latin: "Al-Fajr" },
  { arabic: "البلد", latin: "Al-Balad" },
  { arabic: "الشمس", latin: "Ash-Shams" },
  { arabic: "الليل", latin: "Al-Layl" },
  { arabic: "الضحى", latin: "Aḍ-Ḍuḥā" },
  { arabic: "الشرح", latin: "Ash-Sharḥ" },
  { arabic: "التين", latin: "At-Tīn" },
  { arabic: "العلق", latin: "Al-ʿAlaq" },
  { arabic: "القدر", latin: "Al-Qadr" },
  { arabic: "البينة", latin: "Al-Bayyinah" },
  { arabic: "الزلزلة", latin: "Az-Zalzalah" },
  { arabic: "العاديات", latin: "Al-ʿĀdiyāt" },
  { arabic: "القارعة", latin: "Al-Qāriʿah" },
  { arabic: "التكاثر", latin: "At-Takāthur" },
  { arabic: "العصر", latin: "Al-ʿAṣr" },
  { arabic: "الهمزة", latin: "Al-Humazah" },
  { arabic: "الفيل", latin: "Al-Fīl" },
  { arabic: "قريش", latin: "Quraysh" },
  { arabic: "الماعون", latin: "Al-Māʿūn" },
  { arabic: "الكوثر", latin: "Al-Kawthar" },
  { arabic: "الكافرون", latin: "Al-Kāfirūn" },
  { arabic: "النصر", latin: "An-Naṣr" },
  { arabic: "المسد", latin: "Al-Masad" },
  { arabic: "الإخلاص", latin: "Al-Ikhlāṣ" },
  { arabic: "الفلق", latin: "Al-Falaq" },
  { arabic: "الناس", latin: "An-Nās" },
];

export const SURAH_COUNT = SURAHS.length;

export function surahByNumber(surah: number): Surah | null {
  return SURAHS[surah - 1] ?? null;
}
