/**
 * AUTO-GENERATED by scripts/bundle-celld-migrations.mjs — do not edit by hand.
 *
 * The durable-sqlite migration bundle for the celld RegistryDatabase Durable
 * Object. Regenerate after `pnpm db:generate` (which chains this script):
 *
 *   pnpm celld:db:bundle
 *
 * `migrations/` remains the single source of truth for schema; the SQL text
 * below is generated verbatim from those files.
 */
export const celldJournal = {
    "version": "7",
    "dialect": "sqlite",
    "entries": [
      {
        "idx": 0,
        "version": "6",
        "when": 1782569598842,
        "tag": "0000_cold_joshua_kane",
        "breakpoints": true
      },
      {
        "idx": 1,
        "version": "6",
        "when": 1782581245505,
        "tag": "0001_lying_masked_marvel",
        "breakpoints": true
      },
      {
        "idx": 2,
        "version": "6",
        "when": 1782603086645,
        "tag": "0002_cute_metal_master",
        "breakpoints": true
      },
      {
        "idx": 3,
        "version": "6",
        "when": 1782715628727,
        "tag": "0003_overrated_luke_cage",
        "breakpoints": true
      },
      {
        "idx": 4,
        "version": "6",
        "when": 1782720933452,
        "tag": "0004_brief_big_bertha",
        "breakpoints": true
      },
      {
        "idx": 5,
        "version": "6",
        "when": 1782745453340,
        "tag": "0005_true_photon",
        "breakpoints": true
      },
      {
        "idx": 6,
        "version": "6",
        "when": 1782823794933,
        "tag": "0006_swift_callisto",
        "breakpoints": true
      },
      {
        "idx": 7,
        "version": "6",
        "when": 1782861621000,
        "tag": "0007_agent_memories",
        "breakpoints": true
      },
      {
        "idx": 8,
        "version": "6",
        "when": 1782862276000,
        "tag": "0008_agent_skills",
        "breakpoints": true
      },
      {
        "idx": 9,
        "version": "6",
        "when": 1782908277000,
        "tag": "0009_openai_compatible_providers",
        "breakpoints": true
      },
      {
        "idx": 10,
        "version": "6",
        "when": 1782918119000,
        "tag": "0010_agent_model_modalities",
        "breakpoints": true
      },
      {
        "idx": 11,
        "version": "6",
        "when": 1782921589000,
        "tag": "0011_thread_model_snapshots",
        "breakpoints": true
      },
      {
        "idx": 12,
        "version": "6",
        "when": 1782962057000,
        "tag": "0012_agent_skills_enabled",
        "breakpoints": true
      },
      {
        "idx": 13,
        "version": "6",
        "when": 1782969207000,
        "tag": "0013_attachments_filename",
        "breakpoints": true
      },
      {
        "idx": 14,
        "version": "6",
        "when": 1783044383441,
        "tag": "0014_workspace_sandbox_settings",
        "breakpoints": true
      },
      {
        "idx": 15,
        "version": "6",
        "when": 1783054483309,
        "tag": "0015_nosy_ghost_rider",
        "breakpoints": true
      },
      {
        "idx": 16,
        "version": "6",
        "when": 1783062740824,
        "tag": "0016_abnormal_lady_vermin",
        "breakpoints": true
      },
      {
        "idx": 17,
        "version": "6",
        "when": 1783072530409,
        "tag": "0017_elite_the_hunter",
        "breakpoints": true
      },
      {
        "idx": 18,
        "version": "6",
        "when": 1783095676057,
        "tag": "0018_overconfident_ben_urich",
        "breakpoints": true
      },
      {
        "idx": 19,
        "version": "6",
        "when": 1783232150652,
        "tag": "0019_sandbox_resource_packages",
        "breakpoints": true
      },
      {
        "idx": 20,
        "version": "6",
        "when": 1783439695531,
        "tag": "0020_low_loners",
        "breakpoints": true
      },
      {
        "idx": 21,
        "version": "6",
        "when": 1783480483482,
        "tag": "0021_faulty_mariko_yashida",
        "breakpoints": true
      },
      {
        "idx": 22,
        "version": "6",
        "when": 1783501754984,
        "tag": "0022_glorious_crystal",
        "breakpoints": true
      },
      {
        "idx": 23,
        "version": "6",
        "when": 1783551817691,
        "tag": "0023_ambiguous_lady_bullseye",
        "breakpoints": true
      },
      {
        "idx": 24,
        "version": "6",
        "when": 1783573132591,
        "tag": "0024_simple_darkstar",
        "breakpoints": true
      },
      {
        "idx": 25,
        "version": "6",
        "when": 1783589187917,
        "tag": "0025_odd_thing",
        "breakpoints": true
      },
      {
        "idx": 26,
        "version": "6",
        "when": 1783602727766,
        "tag": "0026_curly_mockingbird",
        "breakpoints": true
      },
      {
        "idx": 27,
        "version": "6",
        "when": 1783646172694,
        "tag": "0027_fantastic_toad_men",
        "breakpoints": true
      },
      {
        "idx": 28,
        "version": "6",
        "when": 1783728104055,
        "tag": "0028_motionless_sentinel",
        "breakpoints": true
      },
      {
        "idx": 29,
        "version": "6",
        "when": 1783739035149,
        "tag": "0029_gorgeous_wendigo",
        "breakpoints": true
      },
      {
        "idx": 30,
        "version": "6",
        "when": 1783746936637,
        "tag": "0030_fat_george_stacy",
        "breakpoints": true
      },
      {
        "idx": 31,
        "version": "6",
        "when": 1783756948173,
        "tag": "0031_flawless_harrier",
        "breakpoints": true
      },
      {
        "idx": 32,
        "version": "6",
        "when": 1783813980516,
        "tag": "0032_perpetual_war_machine",
        "breakpoints": true
      },
      {
        "idx": 33,
        "version": "6",
        "when": 1783819299285,
        "tag": "0033_condemned_pestilence",
        "breakpoints": true
      },
      {
        "idx": 34,
        "version": "6",
        "when": 1783839708053,
        "tag": "0034_sleepy_forge",
        "breakpoints": true
      },
      {
        "idx": 35,
        "version": "6",
        "when": 1783847991475,
        "tag": "0035_curved_vanisher",
        "breakpoints": true
      },
      {
        "idx": 36,
        "version": "6",
        "when": 1783943175193,
        "tag": "0036_far_dragon_man",
        "breakpoints": true
      },
      {
        "idx": 37,
        "version": "6",
        "when": 1783947671680,
        "tag": "0037_modern_spot",
        "breakpoints": true
      },
      {
        "idx": 38,
        "version": "6",
        "when": 1784076336552,
        "tag": "0038_blue_iron_lad",
        "breakpoints": true
      },
      {
        "idx": 39,
        "version": "6",
        "when": 1784104101723,
        "tag": "0039_organic_redwing",
        "breakpoints": true
      },
      {
        "idx": 40,
        "version": "6",
        "when": 1784109549306,
        "tag": "0040_sleepy_lucky_pierre",
        "breakpoints": true
      },
      {
        "idx": 41,
        "version": "6",
        "when": 1784350881773,
        "tag": "0041_chunky_master_chief",
        "breakpoints": true
      },
      {
        "idx": 42,
        "version": "6",
        "when": 1784350899942,
        "tag": "0042_tense_wolfsbane",
        "breakpoints": true
      },
      {
        "idx": 43,
        "version": "6",
        "when": 1784371847328,
        "tag": "0043_bouncy_jack_power",
        "breakpoints": true
      },
      {
        "idx": 44,
        "version": "6",
        "when": 1784420224458,
        "tag": "0044_smiling_sentinel",
        "breakpoints": true
      },
      {
        "idx": 45,
        "version": "6",
        "when": 1784421048144,
        "tag": "0045_gray_crusher_hogan",
        "breakpoints": true
      },
      {
        "idx": 46,
        "version": "6",
        "when": 1784425009279,
        "tag": "0046_tough_baron_zemo",
        "breakpoints": true
      },
      {
        "idx": 47,
        "version": "6",
        "when": 1784477356126,
        "tag": "0047_wakeful_spencer_smythe",
        "breakpoints": true
      },
      {
        "idx": 48,
        "version": "6",
        "when": 1784590203457,
        "tag": "0048_great_wither",
        "breakpoints": true
      },
      {
        "idx": 49,
        "version": "6",
        "when": 1784642361753,
        "tag": "0049_luxuriant_romulus",
        "breakpoints": true
      },
      {
        "idx": 50,
        "version": "6",
        "when": 1784868789664,
        "tag": "0050_serious_eternity",
        "breakpoints": true
      },
      {
        "idx": 51,
        "version": "6",
        "when": 1785427148151,
        "tag": "0051_thread_search_projection",
        "breakpoints": true
      },
      {
        "idx": 52,
        "version": "6",
        "when": 1785427153149,
        "tag": "0052_thread_search_fts",
        "breakpoints": true
      },
      {
        "idx": 53,
        "version": "6",
        "when": 1785454882057,
        "tag": "0053_lovely_steve_rogers",
        "breakpoints": true
      },
      {
        "idx": 54,
        "version": "6",
        "when": 1785540026545,
        "tag": "0054_previous_war_machine",
        "breakpoints": true
      },
      {
        "idx": 55,
        "version": "6",
        "when": 1785543418083,
        "tag": "0055_shallow_electro",
        "breakpoints": true
      },
      {
        "idx": 56,
        "version": "6",
        "when": 1785581081743,
        "tag": "0056_nervous_owl",
        "breakpoints": true
      },
      {
        "idx": 57,
        "version": "6",
        "when": 1785584560093,
        "tag": "0057_hesitant_jean_grey",
        "breakpoints": true
      },
      {
        "idx": 58,
        "version": "6",
        "when": 1785634968391,
        "tag": "0058_brainy_james_howlett",
        "breakpoints": true
      },
      {
        "idx": 59,
        "version": "6",
        "when": 1785897066445,
        "tag": "0059_soft_sumo",
        "breakpoints": true
      }
    ]
  };

export const celldMigrations: Record<string, string> = {
  m0000: `CREATE TABLE \`agents\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`system_prompt\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`model\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_agents_workspace\` ON \`agents\` (\`workspace_id\`);--> statement-breakpoint
CREATE TABLE \`mcp_servers\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`enabled\` integer DEFAULT true NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`mcp_tool_policies\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`server_id\` text NOT NULL,
	\`tool_name\` text NOT NULL,
	\`policy\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`server_id\`) REFERENCES \`mcp_servers\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`provider_configs\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`display_name\` text NOT NULL,
	\`secret_name\` text NOT NULL,
	\`created_at\` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`routine_runs\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`routine_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`due_at\` integer NOT NULL,
	\`thread_id\` text,
	\`status\` text NOT NULL,
	\`error\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`routine_id\`) REFERENCES \`routines\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_routine_runs_routine\` ON \`routine_runs\` (\`routine_id\`,\`created_at\`);--> statement-breakpoint
CREATE INDEX \`idx_routine_runs_due\` ON \`routine_runs\` (\`routine_id\`,\`due_at\`);--> statement-breakpoint
CREATE TABLE \`routines\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`owner_user_id\` text NOT NULL,
	\`agent_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`prompt\` text NOT NULL,
	\`schedule_json\` text NOT NULL,
	\`timezone\` text NOT NULL,
	\`enabled\` integer DEFAULT true NOT NULL,
	\`next_due_at\` integer,
	\`last_fired_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`owner_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`agent_id\`) REFERENCES \`agents\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_routines_due\` ON \`routines\` (\`enabled\`,\`next_due_at\`);--> statement-breakpoint
CREATE INDEX \`idx_routines_workspace\` ON \`routines\` (\`workspace_id\`);--> statement-breakpoint
CREATE TABLE \`sessions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`token_hash\` text NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`sessions_token_hash_unique\` ON \`sessions\` (\`token_hash\`);--> statement-breakpoint
CREATE TABLE \`thread_index\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`agent_id\` text NOT NULL,
	\`title\` text NOT NULL,
	\`source\` text NOT NULL,
	\`routine_id\` text,
	\`routine_run_id\` text,
	\`last_event_id\` text,
	\`last_message_preview\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`agent_id\`) REFERENCES \`agents\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_thread_index_workspace_updated\` ON \`thread_index\` (\`workspace_id\`,\`updated_at\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_index_routine\` ON \`thread_index\` (\`workspace_id\`,\`routine_id\`);--> statement-breakpoint
CREATE TABLE \`users\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`email\` text NOT NULL,
	\`name\` text,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`users_email_unique\` ON \`users\` (\`email\`);--> statement-breakpoint
CREATE TABLE \`workspace_members\` (
	\`workspace_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`role\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	PRIMARY KEY(\`workspace_id\`, \`user_id\`),
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`workspaces\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`created_at\` integer NOT NULL
);
`,
  m0001: `CREATE TABLE \`accounts\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`account_id\` text NOT NULL,
	\`provider_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`access_token\` text,
	\`refresh_token\` text,
	\`id_token\` text,
	\`access_token_expires_at\` integer,
	\`refresh_token_expires_at\` integer,
	\`scope\` text,
	\`password\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`verifications\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`identifier\` text NOT NULL,
	\`value\` text NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer,
	\`updated_at\` integer
);
--> statement-breakpoint
DROP INDEX \`sessions_token_hash_unique\`;--> statement-breakpoint
ALTER TABLE \`sessions\` ADD \`token\` text NOT NULL;--> statement-breakpoint
ALTER TABLE \`sessions\` ADD \`updated_at\` integer NOT NULL;--> statement-breakpoint
ALTER TABLE \`sessions\` ADD \`ip_address\` text;--> statement-breakpoint
ALTER TABLE \`sessions\` ADD \`user_agent\` text;--> statement-breakpoint
CREATE UNIQUE INDEX \`sessions_token_unique\` ON \`sessions\` (\`token\`);--> statement-breakpoint
ALTER TABLE \`sessions\` DROP COLUMN \`token_hash\`;--> statement-breakpoint
ALTER TABLE \`users\` ADD \`email_verified\` integer DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE \`users\` ADD \`image\` text;--> statement-breakpoint
ALTER TABLE \`users\` ADD \`updated_at\` integer NOT NULL;`,
  m0002: `CREATE UNIQUE INDEX \`verifications_identifier_unique\` ON \`verifications\` (\`identifier\`);`,
  m0003: `ALTER TABLE \`thread_index\` ADD \`title_set\` integer DEFAULT false NOT NULL;`,
  m0004: `ALTER TABLE \`agents\` ADD \`show_reasoning\` integer DEFAULT true NOT NULL;`,
  m0005: `CREATE TABLE \`attachments\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`thread_id\` text NOT NULL,
	\`mime_type\` text NOT NULL,
	\`byte_size\` integer NOT NULL,
	\`width\` integer,
	\`height\` integer,
	\`r2_key\` text NOT NULL,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`idx_attachments_thread\` ON \`attachments\` (\`thread_id\`);`,
  m0006: `ALTER TABLE \`thread_index\` ADD \`runtime\` text DEFAULT 'legacy' NOT NULL;`,
  m0007: `CREATE TABLE \`agent_memories\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`workspace_id\` text NOT NULL,
  \`agent_id\` text NOT NULL,
  \`content\` text NOT NULL,
  \`title\` text,
  \`kind\` text DEFAULT 'fact' NOT NULL,
  \`source_thread_id\` text,
  \`created_at\` integer NOT NULL,
  \`updated_at\` integer NOT NULL,
  \`archived_at\` integer,
  FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
  FOREIGN KEY (\`agent_id\`) REFERENCES \`agents\`(\`id\`) ON UPDATE no action ON DELETE no action
);
CREATE INDEX \`idx_agent_memories_agent\` ON \`agent_memories\` (\`workspace_id\`,\`agent_id\`,\`archived_at\`,\`updated_at\`);
CREATE INDEX \`idx_agent_memories_source_thread\` ON \`agent_memories\` (\`source_thread_id\`);
`,
  m0008: `CREATE TABLE \`agent_skills\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`workspace_id\` text NOT NULL,
  \`agent_id\` text NOT NULL,
  \`name\` text NOT NULL,
  \`description\` text NOT NULL,
  \`body\` text NOT NULL,
  \`created_at\` integer NOT NULL,
  \`updated_at\` integer NOT NULL,
  \`archived_at\` integer,
  FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
  FOREIGN KEY (\`agent_id\`) REFERENCES \`agents\`(\`id\`) ON UPDATE no action ON DELETE no action
);
CREATE INDEX \`idx_agent_skills_agent\` ON \`agent_skills\` (\`workspace_id\`,\`agent_id\`,\`archived_at\`);
CREATE INDEX \`idx_agent_skills_name\` ON \`agent_skills\` (\`workspace_id\`,\`agent_id\`,\`name\`);
CREATE UNIQUE INDEX \`idx_agent_skills_active_name_unique\` ON \`agent_skills\` (\`workspace_id\`,\`agent_id\`,\`name\`) WHERE \`archived_at\` IS NULL;
`,
  m0009: `ALTER TABLE \`provider_configs\` ADD \`config_json\` text;
`,
  m0010: `ALTER TABLE agents ADD COLUMN model_input_modalities TEXT NOT NULL DEFAULT '["text"]';
`,
  m0011: `ALTER TABLE thread_index ADD COLUMN model_provider TEXT;
ALTER TABLE thread_index ADD COLUMN model TEXT;
ALTER TABLE thread_index ADD COLUMN model_input_modalities TEXT;
ALTER TABLE thread_index ADD COLUMN show_reasoning INTEGER;

UPDATE thread_index
SET
  model_provider = 'openai-oauth',
  model = 'gpt-5.5',
  model_input_modalities = '["text","image","file"]',
  show_reasoning = 1
WHERE model_provider IS NULL OR model IS NULL OR model_input_modalities IS NULL OR show_reasoning IS NULL;
`,
  m0012: `ALTER TABLE agent_skills ADD COLUMN enabled INTEGER NOT NULL DEFAULT true;
`,
  m0013: `ALTER TABLE attachments ADD COLUMN filename text;
`,
  m0014: `CREATE TABLE \`workspace_sandbox_settings\` (
	\`workspace_id\` text PRIMARY KEY NOT NULL,
	\`enabled\` integer DEFAULT false NOT NULL,
	\`provider\` text DEFAULT 'daytona' NOT NULL,
	\`image\` text DEFAULT '' NOT NULL,
	\`daytona_api_key_secret_name\` text DEFAULT 'sandbox:daytona' NOT NULL,
	\`daytona_api_url\` text,
	\`daytona_target\` text,
	\`idle_timeout_ms\` integer DEFAULT 900000 NOT NULL,
	\`max_process_runtime_ms\` integer DEFAULT 600000 NOT NULL,
	\`limits_json\` text DEFAULT '{}' NOT NULL,
	\`created_at\` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	\`updated_at\` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE \`agents\` ADD \`sandbox_enabled\` integer;--> statement-breakpoint
ALTER TABLE \`agents\` ADD \`sandbox_image\` text;--> statement-breakpoint
ALTER TABLE \`agents\` ADD \`sandbox_idle_timeout_ms\` integer;--> statement-breakpoint
ALTER TABLE \`agents\` ADD \`sandbox_max_process_runtime_ms\` integer;
`,
  m0015: `ALTER TABLE \`agents\` ADD \`sandbox_snapshot\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`snapshot\` text;`,
  m0016: `ALTER TABLE \`agents\` ADD \`sandbox_network_domain_allowlist\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`network_restriction_enabled\` integer DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`network_domain_allowlist\` text DEFAULT '' NOT NULL;`,
  m0017: `ALTER TABLE \`agents\` ADD \`sandbox_env_vars_json\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`env_vars_json\` text;`,
  m0018: `CREATE TABLE \`agent_skill_resources\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`skill_id\` text NOT NULL,
	\`path\` text NOT NULL,
	\`kind\` text NOT NULL,
	\`encoding\` text NOT NULL,
	\`mime_type\` text,
	\`content\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`skill_id\`) REFERENCES \`agent_skills\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX \`idx_agent_skill_resources_skill\` ON \`agent_skill_resources\` (\`skill_id\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_agent_skill_resources_skill_path\` ON \`agent_skill_resources\` (\`skill_id\`,\`path\`);--> statement-breakpoint
ALTER TABLE \`agent_skills\` ADD \`network_domains\` text;`,
  m0019: `ALTER TABLE \`workspace_sandbox_settings\` ADD \`small_snapshot\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`medium_snapshot\` text;`,
  m0020: `ALTER TABLE \`thread_index\` ADD \`archived_at\` integer;--> statement-breakpoint
CREATE INDEX \`idx_thread_index_workspace_archived\` ON \`thread_index\` (\`workspace_id\`,\`archived_at\`);`,
  m0021: `CREATE TABLE \`archived_message\` (
	\`thread_id\` text NOT NULL,
	\`seq\` integer NOT NULL,
	\`payload\` text NOT NULL,
	PRIMARY KEY(\`thread_id\`, \`seq\`)
);
`,
  m0022: `CREATE TABLE \`project_repository_assignments\` (
	\`project_id\` text NOT NULL,
	\`repository_id\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	PRIMARY KEY(\`project_id\`, \`repository_id\`),
	FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`repository_id\`) REFERENCES \`workspace_repositories\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`projects\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`description\` text DEFAULT '' NOT NULL,
	\`custom_instructions\` text DEFAULT '' NOT NULL,
	\`archived_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_projects_workspace_archived\` ON \`projects\` (\`workspace_id\`,\`archived_at\`);--> statement-breakpoint
CREATE TABLE \`thread_repository_snapshots\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`thread_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`project_id\` text NOT NULL,
	\`workspace_repository_id\` text,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`default_branch\` text NOT NULL,
	\`checkout_path_name\` text NOT NULL,
	\`root_directory\` text DEFAULT '' NOT NULL,
	\`setup_command\` text DEFAULT '' NOT NULL,
	\`package_manager\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_thread\` ON \`thread_repository_snapshots\` (\`thread_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_workspace\` ON \`thread_repository_snapshots\` (\`workspace_id\`);--> statement-breakpoint
CREATE TABLE \`workspace_repositories\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`default_branch\` text DEFAULT 'main' NOT NULL,
	\`checkout_path_name\` text NOT NULL,
	\`root_directory\` text DEFAULT '' NOT NULL,
	\`setup_command\` text DEFAULT '' NOT NULL,
	\`package_manager\` text DEFAULT '' NOT NULL,
	\`archived_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_workspace_repositories_workspace_archived\` ON \`workspace_repositories\` (\`workspace_id\`,\`archived_at\`);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`project_id\` text;--> statement-breakpoint
CREATE INDEX \`idx_thread_index_workspace_project_updated\` ON \`thread_index\` (\`workspace_id\`,\`project_id\`,\`updated_at\`);`,
  m0023: `CREATE TABLE \`push_subscriptions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`user_id\` text NOT NULL,
	\`endpoint\` text NOT NULL,
	\`p256dh\` text NOT NULL,
	\`auth\` text NOT NULL,
	\`user_agent\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`last_seen_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_push_subscriptions_user\` ON \`push_subscriptions\` (\`user_id\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_push_subscriptions_endpoint\` ON \`push_subscriptions\` (\`endpoint\`);--> statement-breakpoint
CREATE TABLE \`user_notification_settings\` (
	\`user_id\` text PRIMARY KEY NOT NULL,
	\`browser_push_enabled\` integer DEFAULT false NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`activity_status\` text DEFAULT 'idle' NOT NULL;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`current_turn_started_at\` integer;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`attention_required_at\` integer;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`unread_outcome\` text;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`unread_outcome_at\` integer;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`last_seen_at\` integer;`,
  m0024: `CREATE TABLE \`workspace_privacy_settings\` (
	\`workspace_id\` text PRIMARY KEY NOT NULL,
	\`telemetry_enabled\` integer DEFAULT false NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  m0025: `ALTER TABLE \`thread_index\` RENAME COLUMN "routine_id" TO "automaton_id";--> statement-breakpoint
ALTER TABLE \`thread_index\` RENAME COLUMN "routine_run_id" TO "automaton_run_id";--> statement-breakpoint
CREATE TABLE \`automata\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`owner_user_id\` text NOT NULL,
	\`agent_id\` text NOT NULL,
	\`project_id\` text,
	\`name\` text NOT NULL,
	\`prompt\` text NOT NULL,
	\`schedule_json\` text NOT NULL,
	\`timezone\` text NOT NULL,
	\`enabled\` integer DEFAULT true NOT NULL,
	\`next_due_at\` integer,
	\`last_fired_at\` integer,
	\`archived_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`owner_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`agent_id\`) REFERENCES \`agents\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_automata_due\` ON \`automata\` (\`enabled\`,\`next_due_at\`);--> statement-breakpoint
CREATE INDEX \`idx_automata_workspace\` ON \`automata\` (\`workspace_id\`,\`archived_at\`);--> statement-breakpoint
CREATE TABLE \`automaton_runs\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`automaton_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`due_at\` integer,
	\`trigger\` text NOT NULL,
	\`thread_id\` text,
	\`status\` text NOT NULL,
	\`error\` text,
	\`started_at\` integer,
	\`finished_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`automaton_id\`) REFERENCES \`automata\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_automaton_runs_automaton\` ON \`automaton_runs\` (\`automaton_id\`,\`created_at\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_automaton_runs_due\` ON \`automaton_runs\` (\`automaton_id\`,\`due_at\`) WHERE "automaton_runs"."trigger" = 'scheduled';--> statement-breakpoint
DROP TABLE \`routine_runs\`;--> statement-breakpoint
DROP TABLE \`routines\`;--> statement-breakpoint
DROP INDEX \`idx_thread_index_routine\`;--> statement-breakpoint
CREATE INDEX \`idx_thread_index_automaton\` ON \`thread_index\` (\`workspace_id\`,\`automaton_id\`);`,
  m0026: `ALTER TABLE \`attachments\` ADD \`extracted_text\` text;--> statement-breakpoint
ALTER TABLE \`attachments\` ADD \`extracted_source\` text;--> statement-breakpoint
ALTER TABLE \`attachments\` ADD \`extracted_at\` integer;--> statement-breakpoint
ALTER TABLE \`attachments\` ADD \`extracted_error\` text;--> statement-breakpoint
ALTER TABLE \`attachments\` ADD \`extracted_attempts\` integer DEFAULT 0 NOT NULL;`,
  m0027: `ALTER TABLE \`agents\` ADD \`sandbox_resource_profile\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`provider_config_json\` text;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`default_resource_profile\` text DEFAULT 'small' NOT NULL;--> statement-breakpoint
ALTER TABLE \`workspace_sandbox_settings\` ADD \`recovery_ttl_ms\` integer DEFAULT 86400000 NOT NULL;`,
  m0028: `ALTER TABLE \`automata\` ADD \`notify_mode\` text DEFAULT 'all' NOT NULL;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`outcome_dismissed_at\` integer;`,
  m0029: `CREATE TABLE \`invites\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`token\` text,
	\`inviter_user_id\` text NOT NULL,
	\`email\` text,
	\`status\` text DEFAULT 'pending' NOT NULL,
	\`accepted_user_id\` text,
	\`created_at\` integer NOT NULL,
	\`claimed_at\` integer,
	\`accepted_at\` integer,
	FOREIGN KEY (\`inviter_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`accepted_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`invites_token_unique\` ON \`invites\` (\`token\`);--> statement-breakpoint
CREATE INDEX \`idx_invites_email\` ON \`invites\` (\`email\`);--> statement-breakpoint
CREATE INDEX \`idx_invites_inviter\` ON \`invites\` (\`inviter_user_id\`);--> statement-breakpoint
CREATE TABLE \`waiting_list\` (
	\`email\` text PRIMARY KEY NOT NULL,
	\`attempts\` integer DEFAULT 1 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
`,
  m0030: `ALTER TABLE \`automata\` ADD \`disabled_reason\` text;`,
  m0031: `CREATE TABLE \`user_voice_settings\` (
	\`user_id\` text PRIMARY KEY NOT NULL,
	\`language\` text DEFAULT 'en' NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  m0032: `ALTER TABLE \`automata\` ADD \`model_provider\` text;--> statement-breakpoint
ALTER TABLE \`automata\` ADD \`model\` text;--> statement-breakpoint
ALTER TABLE \`automata\` ADD \`model_input_modalities\` text;`,
  m0033: `CREATE TABLE \`active_containers\` (
	\`thread_id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`profile\` text NOT NULL,
	\`last_used_at\` integer NOT NULL,
	\`expires_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`idx_active_containers_ws\` ON \`active_containers\` (\`workspace_id\`,\`expires_at\`);`,
  m0034: `ALTER TABLE \`thread_index\` ADD \`archive_skipped_updated_at\` integer;`,
  m0035: `CREATE TABLE \`archived_compaction\` (
	\`thread_id\` text NOT NULL,
	\`seq\` integer NOT NULL,
	\`compaction_id\` text NOT NULL,
	\`from_message_id\` text NOT NULL,
	\`to_message_id\` text NOT NULL,
	\`summary\` text NOT NULL,
	PRIMARY KEY(\`thread_id\`, \`seq\`)
);
`,
  m0036: `CREATE TABLE \`thread_token_usage\` (
	\`thread_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`agent_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`model\` text NOT NULL,
	\`source\` text NOT NULL,
	\`input_tokens\` integer DEFAULT 0 NOT NULL,
	\`cached_input_tokens\` integer DEFAULT 0 NOT NULL,
	\`cache_write_tokens\` integer DEFAULT 0 NOT NULL,
	\`output_tokens\` integer DEFAULT 0 NOT NULL,
	\`reasoning_tokens\` integer DEFAULT 0 NOT NULL,
	\`calls\` integer DEFAULT 0 NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_thread_token_usage_key\` ON \`thread_token_usage\` (\`thread_id\`,\`provider\`,\`model\`,\`source\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_token_usage_thread\` ON \`thread_token_usage\` (\`thread_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_token_usage_workspace\` ON \`thread_token_usage\` (\`workspace_id\`);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`last_context_tokens\` integer;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`last_context_window\` integer;`,
  m0037: `ALTER TABLE \`thread_index\` ADD \`last_compact_after_tokens\` integer;`,
  m0038: `CREATE TABLE \`github_app_installations\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`installation_id\` integer NOT NULL,
	\`account_login\` text NOT NULL,
	\`account_type\` text NOT NULL,
	\`repository_selection\` text NOT NULL,
	\`connected_by_user_id\` text NOT NULL,
	\`status\` text DEFAULT 'active' NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_github_app_installations_workspace\` ON \`github_app_installations\` (\`workspace_id\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`uidx_github_app_installations_ws_installation\` ON \`github_app_installations\` (\`workspace_id\`,\`installation_id\`);`,
  m0039: `CREATE TABLE \`environments\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`description\` text DEFAULT '' NOT NULL,
	\`setup_script\` text DEFAULT '' NOT NULL,
	\`sandbox_env_vars_json\` text DEFAULT '{}' NOT NULL,
	\`archived_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_environments_workspace_archived\` ON \`environments\` (\`workspace_id\`,\`archived_at\`);--> statement-breakpoint
CREATE TABLE \`environment_repositories\` (
	\`environment_id\` text NOT NULL,
	\`repository_id\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	PRIMARY KEY(\`environment_id\`, \`repository_id\`),
	FOREIGN KEY (\`environment_id\`) REFERENCES \`environments\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`repository_id\`) REFERENCES \`workspace_repositories\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`thread_environment_snapshots\` (
	\`thread_id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`environment_id\` text,
	\`name\` text NOT NULL,
	\`setup_script\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`__new_thread_repository_snapshots\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`thread_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`project_id\` text,
	\`environment_id\` text,
	\`workspace_repository_id\` text,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`default_branch\` text NOT NULL,
	\`checkout_path_name\` text NOT NULL,
	\`root_directory\` text DEFAULT '' NOT NULL,
	\`setup_command\` text DEFAULT '' NOT NULL,
	\`package_manager\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`environment_id\`) REFERENCES \`environments\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO \`__new_thread_repository_snapshots\`("id", "thread_id", "workspace_id", "project_id", "workspace_repository_id", "name", "url", "default_branch", "checkout_path_name", "root_directory", "setup_command", "package_manager", "created_at") SELECT "id", "thread_id", "workspace_id", "project_id", "workspace_repository_id", "name", "url", "default_branch", "checkout_path_name", "root_directory", "setup_command", "package_manager", "created_at" FROM \`thread_repository_snapshots\`;--> statement-breakpoint
DROP TABLE \`thread_repository_snapshots\`;--> statement-breakpoint
ALTER TABLE \`__new_thread_repository_snapshots\` RENAME TO \`thread_repository_snapshots\`;--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_thread\` ON \`thread_repository_snapshots\` (\`thread_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_workspace\` ON \`thread_repository_snapshots\` (\`workspace_id\`);--> statement-breakpoint
ALTER TABLE \`projects\` ADD \`default_environment_id\` text REFERENCES environments(id);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`environment_id\` text REFERENCES environments(id);--> statement-breakpoint
ALTER TABLE \`workspace_repositories\` ADD \`source_installation_id\` text REFERENCES github_app_installations(id);--> statement-breakpoint
ALTER TABLE \`workspace_repositories\` ADD \`github_repo_id\` integer;--> statement-breakpoint
ALTER TABLE \`workspace_repositories\` ADD \`access_status\` text DEFAULT 'ok' NOT NULL;
`,
  m0040: `DROP TABLE \`project_repository_assignments\`;`,
  m0041: `-- HAND-REWRITTEN for D1 compatibility (see task notes / final-fix-report.md).
--
-- drizzle generated a \`__new_\`-table rebuild for \`projects\`, \`thread_index\`, and
-- \`thread_repository_snapshots\` to drop their environment/workspace_repository
-- columns. That approach CANNOT apply on a populated remote D1:
--   * D1 ignores \`PRAGMA foreign_keys=OFF\` and enforces FKs on the live
--     connection, so \`DROP TABLE projects\` / \`DROP TABLE thread_index\` fail —
--     those tables are referenced by many others (messages, events, snapshots…),
--     and you cannot drop a referenced parent.
--   * Adding \`PRAGMA defer_foreign_keys=ON\` (which D1 DOES honor) got past the
--     drops, but D1's commit-time integrity check still rejected the batch.
--
-- Fix, verified by replaying against a full export of the real remote DB
-- (foreign_key_check = 0 violations, all rows preserved):
--   * \`projects.default_environment_id\` and \`thread_index.environment_id\` are
--     inline-FK columns → drop them in place with ALTER TABLE ... DROP COLUMN
--     (no parent-table drop, so nothing to block the FK).
--   * \`thread_repository_snapshots\` carries a TABLE-LEVEL FK on \`environment_id\`
--     that DROP COLUMN cannot remove, so it still needs drizzle's \`__new_\`
--     rebuild — but it is a leaf table (nothing references it), so dropping and
--     renaming it succeeds. Its rebuild block below is drizzle's verbatim.
--   * The four standalone env tables are dropped last, child-first.
-- \`defer_foreign_keys=ON\` is kept as a belt-and-suspenders for the drops.
-- Produces the identical final schema drizzle intended (schema.ts is the source
-- of truth). Verified via a clean local \`pnpm run db:migrate:local\` through 0042.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
PRAGMA defer_foreign_keys=ON;--> statement-breakpoint
ALTER TABLE \`projects\` DROP COLUMN \`default_environment_id\`;--> statement-breakpoint
ALTER TABLE \`thread_index\` DROP COLUMN \`environment_id\`;--> statement-breakpoint
CREATE TABLE \`__new_thread_repository_snapshots\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`thread_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`project_id\` text,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`default_branch\` text NOT NULL,
	\`checkout_path_name\` text NOT NULL,
	\`root_directory\` text DEFAULT '' NOT NULL,
	\`setup_command\` text DEFAULT '' NOT NULL,
	\`package_manager\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`project_id\`) REFERENCES \`projects\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO \`__new_thread_repository_snapshots\`("id", "thread_id", "workspace_id", "project_id", "name", "url", "default_branch", "checkout_path_name", "root_directory", "setup_command", "package_manager", "created_at") SELECT "id", "thread_id", "workspace_id", "project_id", "name", "url", "default_branch", "checkout_path_name", "root_directory", "setup_command", "package_manager", "created_at" FROM \`thread_repository_snapshots\`;--> statement-breakpoint
DROP TABLE \`thread_repository_snapshots\`;--> statement-breakpoint
ALTER TABLE \`__new_thread_repository_snapshots\` RENAME TO \`thread_repository_snapshots\`;--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_thread\` ON \`thread_repository_snapshots\` (\`thread_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_repository_snapshots_workspace\` ON \`thread_repository_snapshots\` (\`workspace_id\`);--> statement-breakpoint
DROP TABLE \`environment_repositories\`;--> statement-breakpoint
DROP TABLE \`thread_environment_snapshots\`;--> statement-breakpoint
DROP TABLE \`workspace_repositories\`;--> statement-breakpoint
DROP TABLE \`environments\`;
`,
  m0042: `CREATE TABLE \`thread_workbench_snapshots\` (
	\`thread_id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`workbench_id\` text,
	\`name\` text NOT NULL,
	\`setup_script\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`workbench_repositories\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workbench_id\` text NOT NULL,
	\`source\` text NOT NULL,
	\`name\` text NOT NULL,
	\`url\` text NOT NULL,
	\`github_repo_id\` integer,
	\`source_installation_id\` text,
	\`access_status\` text DEFAULT 'ok' NOT NULL,
	\`checkout_path_name\` text NOT NULL,
	\`default_branch\` text DEFAULT 'main' NOT NULL,
	\`root_directory\` text DEFAULT '' NOT NULL,
	\`setup_command\` text DEFAULT '' NOT NULL,
	\`package_manager\` text DEFAULT '' NOT NULL,
	\`created_at\` integer NOT NULL,
	FOREIGN KEY (\`workbench_id\`) REFERENCES \`workbenches\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`source_installation_id\`) REFERENCES \`github_app_installations\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_workbench_repositories_workbench\` ON \`workbench_repositories\` (\`workbench_id\`);--> statement-breakpoint
CREATE TABLE \`workbenches\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`description\` text DEFAULT '' NOT NULL,
	\`setup_script\` text DEFAULT '' NOT NULL,
	\`sandbox_env_vars_json\` text DEFAULT '{}' NOT NULL,
	\`archived_at\` integer,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX \`idx_workbenches_workspace_archived\` ON \`workbenches\` (\`workspace_id\`,\`archived_at\`);--> statement-breakpoint
ALTER TABLE \`projects\` ADD \`default_workbench_id\` text REFERENCES workbenches(id);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`workbench_id\` text REFERENCES workbenches(id);--> statement-breakpoint
ALTER TABLE \`thread_repository_snapshots\` ADD \`workbench_id\` text;`,
  m0043: `ALTER TABLE \`automata\` ADD \`workbench_id\` text;`,
  m0044: `ALTER TABLE \`workbenches\` ADD \`resource_profile\` text DEFAULT 'small' NOT NULL;`,
  m0045: `ALTER TABLE \`thread_workbench_snapshots\` ADD \`resource_profile\` text;`,
  m0046: `ALTER TABLE \`thread_index\` ADD \`workbench_switch_pending_at\` integer;`,
  m0047: `CREATE TABLE \`feedback_admin_reads\` (
	\`report_id\` text NOT NULL,
	\`admin_user_id\` text NOT NULL,
	\`seen_at\` integer NOT NULL,
	PRIMARY KEY(\`report_id\`, \`admin_user_id\`),
	FOREIGN KEY (\`report_id\`) REFERENCES \`feedback_reports\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`admin_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`feedback_report_attachments\` (
	\`report_id\` text NOT NULL,
	\`attachment_id\` text NOT NULL,
	\`ordinal\` integer NOT NULL,
	PRIMARY KEY(\`report_id\`, \`attachment_id\`),
	FOREIGN KEY (\`report_id\`) REFERENCES \`feedback_reports\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`attachment_id\`) REFERENCES \`attachments\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_feedback_report_attachment_order\` ON \`feedback_report_attachments\` (\`report_id\`,\`ordinal\`);--> statement-breakpoint
CREATE TABLE \`feedback_reports\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`reporter_user_id\` text NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`thread_id\` text NOT NULL,
	\`interview_id\` text NOT NULL,
	\`from_message_id\` text NOT NULL,
	\`to_message_id\` text NOT NULL,
	\`category\` text NOT NULL,
	\`title\` text NOT NULL,
	\`narrative\` text NOT NULL,
	\`reproduction_steps_json\` text NOT NULL,
	\`expected_behavior\` text,
	\`actual_behavior\` text,
	\`frequency\` text,
	\`impact\` text,
	\`diagnostics_json\` text NOT NULL,
	\`idempotency_key\` text NOT NULL,
	\`submitted_at\` integer NOT NULL,
	FOREIGN KEY (\`reporter_user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`feedback_reports_idempotency_key_unique\` ON \`feedback_reports\` (\`idempotency_key\`);--> statement-breakpoint
CREATE INDEX \`idx_feedback_reports_submitted\` ON \`feedback_reports\` (\`submitted_at\`,\`id\`);--> statement-breakpoint
CREATE INDEX \`idx_feedback_reports_reporter\` ON \`feedback_reports\` (\`reporter_user_id\`,\`submitted_at\`);--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_feedback_reports_interview\` ON \`feedback_reports\` (\`thread_id\`,\`interview_id\`);--> statement-breakpoint
CREATE TABLE \`feedback_threads\` (
	\`user_id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`thread_id\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`feedback_threads_thread_id_unique\` ON \`feedback_threads\` (\`thread_id\`);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`kind\` text DEFAULT 'regular' NOT NULL;`,
  m0048: `ALTER TABLE \`workbenches\` ADD \`sandbox_network_domain_allowlist\` text DEFAULT '' NOT NULL;`,
  m0049: `ALTER TABLE \`workspaces\` ADD \`flags_json\` text DEFAULT '{}' NOT NULL;`,
  m0050: `CREATE TABLE \`workbench_secret_names\` (
	\`workbench_id\` text NOT NULL,
	\`name\` text NOT NULL,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`workbench_id\`, \`name\`),
	FOREIGN KEY (\`workbench_id\`) REFERENCES \`workbenches\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE \`workbenches\` ADD \`secret_names_backfilled\` integer DEFAULT false NOT NULL;`,
  m0051: `CREATE TABLE \`thread_search_messages\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`thread_id\` text NOT NULL,
	\`message_id\` text NOT NULL,
	\`role\` text NOT NULL,
	\`created_at\` integer,
	\`content\` text NOT NULL,
	\`content_hash\` text NOT NULL,
	\`source_hash\` text NOT NULL,
	\`indexed_revision\` integer NOT NULL,
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (\`thread_id\`) REFERENCES \`thread_index\`(\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`idx_thread_search_messages_thread_message\` ON \`thread_search_messages\` (\`thread_id\`,\`message_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_search_messages_workspace_thread\` ON \`thread_search_messages\` (\`workspace_id\`,\`thread_id\`);--> statement-breakpoint
CREATE INDEX \`idx_thread_search_messages_thread_created\` ON \`thread_search_messages\` (\`thread_id\`,\`created_at\`);--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`search_indexed_through\` integer;`,
  m0052: `CREATE VIRTUAL TABLE thread_search_fts USING fts5(
  content,
  content='thread_search_messages',
  content_rowid='id',
  tokenize='unicode61'
);

CREATE TRIGGER thread_search_messages_ai AFTER INSERT ON thread_search_messages BEGIN
  INSERT INTO thread_search_fts(rowid, content) VALUES (new.id, new.content);
END;

CREATE TRIGGER thread_search_messages_ad AFTER DELETE ON thread_search_messages BEGIN
  INSERT INTO thread_search_fts(thread_search_fts, rowid, content)
  VALUES ('delete', old.id, old.content);
END;

CREATE TRIGGER thread_search_messages_au AFTER UPDATE OF content ON thread_search_messages BEGIN
  INSERT INTO thread_search_fts(thread_search_fts, rowid, content)
  VALUES ('delete', old.id, old.content);
  INSERT INTO thread_search_fts(rowid, content) VALUES (new.id, new.content);
END;`,
  m0053: `ALTER TABLE \`thread_index\` ADD \`search_repair_attempts\` integer;`,
  m0054: `CREATE TABLE \`provider_model_catalogs\` (
	\`workspace_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`models_json\` text NOT NULL,
	\`source\` text NOT NULL,
	\`fetched_at\` integer NOT NULL,
	PRIMARY KEY(\`workspace_id\`, \`provider\`),
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE \`provider_model_whitelists\` (
	\`workspace_id\` text NOT NULL,
	\`provider\` text NOT NULL,
	\`models_json\` text NOT NULL,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`workspace_id\`, \`provider\`),
	FOREIGN KEY (\`workspace_id\`) REFERENCES \`workspaces\`(\`id\`) ON UPDATE no action ON DELETE no action
);
`,
  m0055: `ALTER TABLE \`thread_index\` ADD \`recent_dismissed_at\` integer;`,
  m0056: `ALTER TABLE \`agents\` ADD \`reasoning_effort\` text DEFAULT 'medium' NOT NULL;--> statement-breakpoint
ALTER TABLE \`agents\` ADD \`model_supports_reasoning\` integer;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`reasoning_effort\` text;--> statement-breakpoint
ALTER TABLE \`thread_index\` ADD \`model_supports_reasoning\` integer;--> statement-breakpoint
-- Hand-added backfill (see docs/superpowers/specs/2026-08-01-composer-reasoning-effort-design.md).
-- \`show_reasoning = 0\` used to mean "do not think at all", not merely "hide the
-- thinking". Without this, every such row silently starts buying reasoning
-- tokens on its next turn. drizzle only emits the ALTERs above, and the
-- alternatives (a hand-edited journal, or resolving this at read time) are worse.
UPDATE \`agents\` SET \`reasoning_effort\` = 'off' WHERE \`show_reasoning\` = 0;--> statement-breakpoint
-- NULL rows are left NULL: they inherit from the agent, which was just fixed.
UPDATE \`thread_index\` SET \`reasoning_effort\` = 'off' WHERE \`show_reasoning\` = 0;
`,
  m0057: `CREATE TABLE \`model_capability_catalog\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`payload_json\` text NOT NULL,
	\`fetched_at\` integer NOT NULL
);
`,
  m0058: `ALTER TABLE \`user_notification_settings\` ADD \`push_preview_enabled\` integer DEFAULT true NOT NULL;`,
  m0059: `CREATE TABLE \`artifacts\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`workspace_id\` text NOT NULL,
	\`thread_id\` text NOT NULL,
	\`title\` text NOT NULL,
	\`entry_path\` text NOT NULL,
	\`file_count\` integer NOT NULL,
	\`byte_size\` integer NOT NULL,
	\`r2_prefix\` text NOT NULL,
	\`status\` text DEFAULT 'active' NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX \`idx_artifacts_thread\` ON \`artifacts\` (\`thread_id\`);`,
};
